### ISSUE TITLE
Issue LSTM for IMDB

### ISSUE THREAD

**Issue by PierreBiousse** [shap/shap#218]
Hello Scott,

Thanks a lot for your wonderful package with Shap !

I receive this message when running the LSTM example:
"AssertionError: Minimum is not known to be either linear or a supported non-linearity! Please post this as a GitHub issue so Minimum can potentially be included in the list of supported ops."

Do you have an idea of how I could fix it ?

Best,

Pierre

**Comment by amirjalilifard** [comment]
I also get the same error and I posted it. If you could find the solution, please let me know!
Regards

**Comment by slundberg** [comment]
I think this showed up recently with newer TF versions. I just pushed a fix to github which will go out to pip with v0.23.

**Comment by PierreBiousse** [comment]
Ok thanks Scott !

**Comment by amirjalilifard** [comment]
How can I update the current SHAP to the version with fixed error?
I am still getting the '**AssertionError: Minimum is not known to be either linear or a supported non-linearity!**' error!

**Comment by amirjalilifard** [comment]
**AssertionError: Minimum is not known to be either linear or a supported non-linearity!**

**Comment by makcedward** [comment]
@pbcacao @amirjalilifard 
You may consider to check out this temporary solution #188

**Comment by slundberg** [comment]
This should be fixed now in 0.23. Let me know if you still have any issues!
