### ISSUE TITLE
TreeExplainer expected_value is `None`?

### ISSUE THREAD

**Issue by katrienbaert** [shap/shap#316]
First of all, thanks for creating this wonderful module, it's been really helpful already!

I'm back to using SHAP for explaining predictions from my xgboost model and have an issue that the TreeExplainer is returning `None` as `expected_value`.  The `shap_values` are calculated fine.
This happens today both in version 0.24.0 (which didn't have the __version__ attribute yet) and 0.25.1, but worked fine in version 0.24.0 a couple of weeks ago (Sept 21st). 
Python version 3.7 (may have been 3.6 on Sept 21st).

```python
print(shap.__version__)
# create TreeExplainer
print(type(model))
shap_explainer = shap.TreeExplainer(model)
shap_expected_value = shap_explainer.expected_value
print(shap_expected_value) 
# extract shape values
shap_values = shap_explainer.shap_values(X)
print(shap_values)
```
has output 
```python
0.25.1
<class 'xgboost.core.Booster'>
None
[[ 0.00000000e+00  1.15434974e-02  2.74908263e-02 -1.61563791e-02
  -2.40031220e-02  4.00882438e-02  6.08998537e-03  8.60848557e-03
  -1.20777711e-02  1.96460057e-02  7.34563684e-03  1.82318385e-03
   4.45002178e-03  4.41195589e-04 -4.07342683e-04 -4.96894820e-03
...
```

This is not a blocker since I can calculate the expected value myself, but I guess this is not an expected behaviour? Or am I completely missing out on something?

Thanks for your feedback!

**Comment by slundberg** [comment]
I should fix this, but the problem here is that I don't precompute the expected_value for xgboost models during __init__. That means it won't get filled in until the `shap_values` method is called. So if you add `print(shap_explainer.expected_value)` as the last line it should work.

**Comment by katrienbaert** [comment]
Hi Scott, thanks for clarifying. 
This works and also explains why I did get to see the `expected_value` at some point.

**Comment by fingoldo** [comment]
Looks like this is still not fixed. Having same issue with CatBoostClassifier now.

**Comment by aoelvp94** [comment]
Same here :pray:
