### ISSUE TITLE
BUG: shap.plots.heatmap() can't handle Explanation without feature_names

### ISSUE THREAD

**Issue by ivanightingale** [shap/shap#3195]
### Issue Description

In `shap.plots.beeswarm()`, if the input `Explanation` does not have specified `feature_names`, default names are created which is done here:
https://github.com/shap/shap/blob/63223e11eb651dc22b802647526b6bb8d0a02293/shap/plots/_beeswarm.py#L155-L156

But `shap.plots.heatmap()` does not. This causes an error at the line below, if the input `Explanation` doesn't have `feature_names` specified (it is `None`):
https://github.com/shap/shap/blob/63223e11eb651dc22b802647526b6bb8d0a02293/shap/plots/_heatmap.py#L81

### Minimal Reproducible Example

```python
import numpy as np
import xgboost
import shap

# create data
X = np.array([[1,1,1], [2,2,2], [3,3,3]])
y = np.array([1,2,3])
model = xgboost.XGBRegressor().fit(X, y)

explainer = shap.Explainer(model)
shap_values = explainer(X)

shap.plots.heatmap(shap_values)  # changing to shap.plots.beeswarm works
```

### Traceback

```shell
Traceback (most recent call last):
  File "<...>.py", line 14, in <module>
    shap.plots.heatmap(shap_values)
  File "/<...>/.conda/envs/env/lib/python3.9/site-packages/shap/plots/_heatmap.py", line 81, in heatmap
    feature_names = np.array(shap_values.feature_names)[feature_order]
IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed
```

### Expected Behavior

A potential remedy is to add code in `shap.plots.heatmap()` similar to that in `shap.plots.beeswarm()` mentioned above to create default feature names when `feature_names` is `None` in the `Explanation`. Another option is to make `Explanation` automatically set default `feature_names` when it is not provided. It's also surprising that this problem was not caught by tests; it should be common (e.g. in neural network models) for features to be represented by arrays that don't keep track of feature names.

### Bug report checklist

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest release](https://github.com/shap/shap/releases) of shap.
- [X] I have confirmed this bug exists on the [master branch](https://github.com/shap/shap/blob/master/CONTRIBUTING.md#installing-from-the-master-branch) of shap.
- [X] I'd be interested in making a PR to fix this bug

### Installed Versions

0.44.0

**Comment by thatlittleboy** [comment]
> I do not have a minimal reproducible example (also I believe the nature of the problem is clear enough).

The minimal example is not just for illustrating the issue/bug, it also gives the maintainers a starting point (we'll use the example to make sure that the issue being reported is resolved properly). If you don't provide the example, it means that we need to do so.

Also, it gives us a bit more context, e.g. why is your `feature_names` None in your Explanation? Are you creating your own, or does it come from one of our Explainers? It could help uncover other underlying problems in the code base.

So please do provide a minimal working example @ivanightingale

**Comment by ivanightingale** [comment]
The issue is still present in the most current version. I've updated a minimal example. @thatlittleboy @dsgibbons
