### ISSUE TITLE
TypeError: In v0.20, force plot now requires the base value as the first parameter! Try shap.plots.force(explainer.expected_value, shap_values) or for multi-output models try shap.plots.force(explainer.expected_value[0], shap_values[0]).

### ISSUE THREAD

**Issue by craftsliu** [shap/shap#3664]
### Issue Description

run this demo:https://github.com/shap/shap/blob/master/notebooks/tabular_examples/tree_based_models/Census%20income%20classification%20with%20LightGBM.ipynb
![image](https://github.com/shap/shap/assets/3487271/26cedf9b-e6dc-4a7f-ae79-a92372a5e44f)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_52792/960682606.py in ()
----> 1 shap.force_plot(
      2     explainer.expected_value, shap_values.values[1, :], X_display.iloc[0, :]
      3 )

~/anaconda3/envs/myenv/lib/python3.8/site-packages/shap/plots/_force.py in force(base_value, shap_values, features, feature_names, out_names, link, plot_cmap, matplotlib, show, figsize, ordering_keys, ordering_keys_time_format, text_rotation, contribution_threshold)
    128                 "shap.plots.force(explainer.expected_value[0], shap_values[0])."
    129             )
--> 130             raise TypeError(emsg)
    131 
    132     if isinstance(shap_values, list):

TypeError: In v0.20, force plot now requires the base value as the first parameter! Try shap.plots.force(explainer.expected_value, shap_values) or for multi-output models try shap.plots.force(explainer.expected_value[0], shap_values[0]).

sample order by similarity

f(x)
<Figure size 800x630 with 2 Axes>

### Minimal Reproducible Example

```python
import lightgbm as lgb
from sklearn.model_selection import train_test_split

import shap

# print the JS visualization code to the notebook
shap.initjs()

X, y = shap.datasets.adult()
X_display, y_display = shap.datasets.adult(display=True)

# create a train/test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=7)
d_train = lgb.Dataset(X_train, label=y_train)
d_test = lgb.Dataset(X_test, label=y_test)

params = {
    "max_bin": 512,
    "learning_rate": 0.05,
    "boosting_type": "gbdt",
    "objective": "binary",
    "metric": "binary_logloss",
    "num_leaves": 10,
    "verbose": -1,
    "min_data": 100,
    "boost_from_average": True,
    "early_stopping_round": 50,
}

model = lgb.train(
    params,
    d_train,
    10000,
    valid_sets=[d_test],
)
explainer = shap.TreeExplainer(model)
shap_values = explainer(X)
shap.force_plot(
    explainer.expected_value, shap_values.values[1, :], X_display.iloc[0, :]
)
```

### Traceback

```shell
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_52792/960682606.py in ()
----> 1 shap.force_plot(
      2     explainer.expected_value, shap_values.values[1, :], X_display.iloc[0, :]
      3 )

~/anaconda3/envs/myenv/lib/python3.8/site-packages/shap/plots/_force.py in force(base_value, shap_values, features, feature_names, out_names, link, plot_cmap, matplotlib, show, figsize, ordering_keys, ordering_keys_time_format, text_rotation, contribution_threshold)
    128                 "shap.plots.force(explainer.expected_value[0], shap_values[0])."
    129             )
--> 130             raise TypeError(emsg)
    131 
    132     if isinstance(shap_values, list):

TypeError: In v0.20, force plot now requires the base value as the first parameter! Try shap.plots.force(explainer.expected_value, shap_values) or for multi-output models try shap.plots.force(explainer.expected_value[0], shap_values[0]).

sample order by similarity

f(x)
<Figure size 800x630 with 2 Axes>
```

### Bug report checklist

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest release](https://github.com/shap/shap/releases) of shap.
- [X] I have confirmed this bug exists on the [master branch](https://github.com/shap/shap/blob/master/CONTRIBUTING.md#installing-from-the-master-branch) of shap.
- [ ] I'd be interested in making a PR to fix this bug

### Installed Versions

0.44.1

**Comment by IlyaSwallow** [comment]
I have the same bug(

**Comment by nprime496** [comment]
+1

**Comment by thatlittleboy** [comment]
I can't reproduce this bug (using the MWE in the original post above) on the latest version 0.46.0.  
It might have been fixed recently after we standardized the shape of expected value and shap values returned by the TreeExplainer for various Tree ensemble models.

![image](https://github.com/user-attachments/assets/3ac715d3-631f-4c72-90a4-efbabf155c93)

If anyone can confirm that this issue persists >= version 0.46.0, feel free to reply here with a **reproducible example** and I'll be happy to reopen the issue.
Thanks.

**Comment by Nacriema** [comment]
I had the same issue. Does this problem related to the version of SHAP? Currently I'm using SHAP `0.44.1`. And followed the visualization steps like the [document](https://shap.readthedocs.io/en/latest/example_notebooks/tabular_examples/tree_based_models/Census%20income%20classification%20with%20LightGBM.html). 

Edited: By following the example script at [`v.0.44.1`](https://github.com/shap/shap/blob/v0.44.1/docs/notebooks/tree_explainer/Census%20income%20classification%20with%20LightGBM.html), then everything works like a charm.

**Comment by MichealgodJordan** [comment]
Same iuess and it still isn't working for shap.plots.force with excatly same parameters, no matter changing  explainer.expected_value with explainer.expected_value[0] or not. (I am sure that it is not a list, but a ndarray).
