### ISSUE TITLE
TreeExplainer on LightGBM model throws JSONDecode Error

### ISSUE THREAD

**Issue by Ashish-Tripathy** [shap/shap#620]
Hi I have trained a LightGBM on my data. But I am unable to create a TreeExplainer on the model.
 Please see the code below:

```
params = {
    "max_bin": 512,
    "learning_rate": 0.05,
    "boosting_type": "gbdt",
    "objective": "binary",
    "metric": "binary_logloss",
    "num_leaves": 10,
    "verbose": -1,
    "min_data": 100,
    "boost_from_average": True
}

model = lgb.train(params, d_train, 1000, valid_sets=[d_test], early_stopping_rounds=50, verbose_eval=10)

shap.initjs()
explainer = shap.TreeExplainer(model)
shap_values = explainer.shap_values(X)
```

Error Log:

```
JSONDecodeError                           Traceback (most recent call last)
<ipython-input-10-ea79d715786a> in <module>

      2 shap.initjs()
----> 3 explainer = shap.TreeExplainer(model)
      4 shap_values = explainer.shap_values(X)


~\AppData\Local\Continuum\anaconda3\envs\work_fstests\lib\site-packages\shap\explainers\tree.py in __init__(self, model, data, model_output, feature_dependence)
     94         self.feature_dependence = feature_dependence
     95         self.expected_value = None
---> 96         self.model = TreeEnsemble(model, self.data, self.data_missing)
     97 
     98         assert feature_dependence in feature_dependence_codes, "Invalid feature_dependence option!"

~\AppData\Local\Continuum\anaconda3\envs\work_fstests\lib\site-packages\shap\explainers\tree.py in __init__(self, model, data, data_missing)
    534             self.model_type = "lightgbm"
    535             self.original_model = model
--> 536             tree_info = self.original_model.dump_model()["tree_info"]
    537             try:
    538                 self.trees = [Tree(e, data=data, data_missing=data_missing) for e in tree_info]

~\AppData\Local\Continuum\anaconda3\envs\work_fstests\lib\site-packages\lightgbm\basic.py in dump_model(self, num_iteration, start_iteration)
   2151                 ctypes.byref(tmp_out_len),
   2152                 ptr_string_buffer))
-> 2153         ret = json.loads(string_buffer.value.decode())
   2154         ret['pandas_categorical'] = json.loads(json.dumps(self.pandas_categorical,
   2155                                                           default=json_default_with_numpy))

~\AppData\Local\Continuum\anaconda3\envs\work_fstests\lib\json\__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    346             parse_int is None and parse_float is None and
    347             parse_constant is None and object_pairs_hook is None and not kw):
--> 348         return _default_decoder.decode(s)
    349     if cls is None:
    350         cls = JSONDecoder

~\AppData\Local\Continuum\anaconda3\envs\work_fstests\lib\json\decoder.py in decode(self, s, _w)
    335 
    336         """
--> 337         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    338         end = _w(s, end).end()
    339         if end != len(s):

~\AppData\Local\Continuum\anaconda3\envs\work_fstests\lib\json\decoder.py in raw_decode(self, s, idx)
    351         """
    352         try:
--> 353             obj, end = self.scan_once(s, idx)
    354         except StopIteration as err:
    355             raise JSONDecodeError("Expecting value", s, err.value) from None

JSONDecodeError: Invalid \escape: line 9 column 36 (char 205)

```

This is happening only with lightgbm, not with XGboost and CatBoost. Please help to resolve this.

**Comment by firmai** [comment]
I have never received this message before, but as you mentioned, it now crept up. Any solution would be greatly appreciated. Edit, @slundberg is currently defending his dissertation, It doesn't matter what version of SHAP or LightGBM you use the problem persists. 

The following is a quick fix making me think there is something faulty with the column titles.

`df = df.rename(columns={x:y for x,y in zip(df.columns,range(0,len(df.columns)))})`

**Comment by imatiach-msft** [comment]
@firmai @Ashish-Tripathy I believe this is an issue with lightgbm, adding @guolinke .  I am also seeing this issue in our builds.  It may have been fixed already in lightgbm (and then it would be in 2.2.4 version), here is the related issue and fix:
https://github.com/microsoft/LightGBM/issues/2130
https://github.com/microsoft/LightGBM/pull/2131
The cause of the error was:
```
In https://github.com/Microsoft/LightGBM/blob/v2.2.3/src/io/tree.cpp#L511 returns from the constructor early, shrinkage_ remains uninitialized and in a very rare case its value is NaN.
```
However, while the error message is the same it is possible that this is a different issue or there are multiple issues.  Note the error is random, so just rerunning usually fixes it.
I was actually hoping to look into this issue eventually when I get a chance.

**Comment by Ashish-Tripathy** [comment]
@firmai The quick fix worked for me. For now, I can contend with this.
@imatiach-msft tried rerunning multiple times, every time the same error. Tried running with previous versions as well but was getting the same error. It seems like the issues are same as you have mentioned.

**Comment by slundberg** [comment]
@Ashish-Tripathy does this still happen with 2.2.4 in LightGBM? It does seem like a LightGBM issue since it is just a standard JSON loader that is crashing while trying to parse the LightGBM output.

**Comment by nepslor** [comment]
Incredibly, downgrading matplotlib from 3.1.3 to 3.0.3, as reported here https://www.gitmemory.com/AlexeyKupershtokh,  solved the issue for me

**Comment by guolinke** [comment]
We fixed more `nan`, `inf` issues in the dumped json file. You can check lightgbm v2.3.0

**Comment by BilguunBatsaikhan** [comment]
@nepslor I have downgraded my matplotlib, the issue persists. 
shap==0.30.1
lightgbm==2.3.0
matplotlib==3.0.3
Can you please specify your shap and lightgbm versions?

**Comment by nepslor** [comment]
@billydentsu I have your same versions. I noticed the bug represented when switching between scientific and non-scientific modes in pycharm. Let me know if you experience the same

**Comment by BilguunBatsaikhan** [comment]
@nepslor I see. @guolinke found out that my issue was caused due to quotes (") appearing in my dataframe's column names.
