### ISSUE TITLE
Tree Explainer error in latest version

### ISSUE THREAD

**Issue by lukemreese** [shap/shap#887]
Additivity assertion error just started popping up after latest update. Model is xgboost regression. Same error when run with shap.TreeExplainer(model, feature_dependence = 'independent')

This was not happening two days ago. Running on databricks runtime 5.5.

AssertionError                            Traceback (most recent call last)
<command-4498218228352399> in <module>()
      2 
      3 explainer = shap.TreeExplainer(model)
----> 4 shap_values = explainer.shap_values(X, y=y.values)

/databricks/python/lib/python3.6/site-packages/shap/explainers/tree.py in shap_values(self, X, y, tree_limit, approximate, check_additivity)
    215 
    216                 if check_additivity and model_output_vals is not None:
--> 217                     self.assert_additivity(out, model_output_vals)
    218 
    219                 return out

/databricks/python/lib/python3.6/site-packages/shap/explainers/tree.py in assert_additivity(self, phi, model_output)
    392                 assert np.max(np.abs(self.expected_value[i] + phi[i].sum(-1) - model_output[:,i])) < 1e-3, err_msg
    393         else:
--> 394             assert np.max(np.abs(self.expected_value + phi.sum(-1) - model_output)) < 1e-3, err_msg
    395 
    396 

AssertionError: Additivity check failed in TreeExplainer! Please report this on GitHub. Consider retrying with the feature_dependence='independent' option.

**Comment by slundberg** [comment]
Any chance you could check to see if changing  1e-3 to 1e-1 helps? Or share a reproducible example? Thanks!

**Comment by srowen** [comment]
Not sure if this helps, but this can be reproduced in the notebook attached to https://databricks.com/blog/2019/06/17/detecting-bias-with-shap.html with the latest SHAP. It's not super hard to re-run after downloading the data, but might take half an hour of fiddling. I don't have an easy way to modify that error tolerance - maybe shap could log the error magnitude?

**Comment by lukemreese** [comment]
@srowen 's notebook is a good reproducible example. I don't think I have an easy way to modify the tolerance either since I'm working in databricks.

**Comment by wwymak** [comment]
hmm, I am also running into this issue... In my case, the difference between the model prediction and the shap values + model average output is > 1 but the % difference is actually tiny (~1e-5). Just wondering if the there is any value in just checking for the relative difference rather than the absolute difference? e.g. I might not care as much if the difference is 5 if the model is predicting 5e8 but would definitly care if the model predicting is 50 🤔

**Comment by srowen** [comment]
Oh that's a good point. In my case it's a regression where values are salaries, so probably tens to hundreds of thousands. That could indeed be it @slundberg . 

So maybe divide through the `abs` by `np.abs(self.expected_value[i] + phi[i].sum(-1))` before `max`?
```
np.max(np.abs(self.expected_value[i] + phi[i].sum(-1) - model_output[:,i])) < 1e-3
```
I can open a pull request if that's directionally right.

**Comment by slundberg** [comment]
Great catch! I added this to prevent any errors from slipping through, but the tolerance is probably too tight for large ranges since XGBoost is float32 and numeric precision might not be enough. I just pushed a fix to master, can you let me know if it helps for you?

**Comment by SaadEphlux** [comment]
I downloaded the latest master from your repo and installed the package however the error still persists.    I am using tree explainer  for XGBRegressor. Would downgrading the shap library solve the issue?

**Comment by pruthvishetty** [comment]
Issue still persists with current PyPi version.

**Comment by joelostblom** [comment]
@slundberg Is this assert intended when `approximate=True`? In the example below I get an assertion error and the value that is being compared (`np.max(np.abs(val - model_output) / (np.abs(val) + 1e-4))`) is around 3000, far above the threshold. If I set `approximate=False`, the same value is around `4e-13` which is well below the tolerance limit.

```python
import shap
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split


X,y = shap.datasets.nhanesi()
X = X.dropna()
y = y[X.index]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=7)

m1 = RandomForestRegressor(n_estimators=20, random_state=0, max_depth=10)
m1.fit(X_train[:1000], y_train[:1000])

explainer = shap.TreeExplainer(m1)
shap_values = explainer.shap_values(X_test, approximate=True)
```

This is on master with the latest changes mentioned above.

**Comment by slundberg** [comment]
@pruthvishetty 0.33 is now live, so that should fix that.

@joelostblom good catch! It still should hold, it was failing because of an issue were the explainer.expected_value was getting set to 0 incorrectly when `approximate=True`. I just pushed a fix to master that addresses this.

@SaadEphlux if you still get errors with the master version send me a notebook that reproduces the problem and I will take a look.

**Comment by maisogjm** [comment]
@slundberg I am seeing the AdditivityCheck failure running the **League of Legends Win Prediction** example on Google Colab (I hope to perform timing benchmarks with and without GPU support). Here is a link to the notebook on Google Colab: [League of Legends Win Prediction](https://colab.research.google.com/drive/1f-oQWQAeFnywq7ccHSwFR0RjLG6F40Wo)
Near the beginning of the notebook, I check the version number of the SHAP library. It is 0.33.0.

I am seeing the same problem with the **NHANES I Survival Model** example. Here is a link to the notebook on Google Colab: [NHANES I Survival Model](https://colab.research.google.com/drive/1VPdsWaCMAEZblR_rXRj9C1brPAYqkcYA)
Here, I tried setting **feature_perturbation** to "interventional", to no avail.

Thanks very much!

**Comment by slundberg** [comment]
@maisogjm I think this has been fixed already on master (it was an issue where the check was too stringent and failed due to small rounding errors). I just pushed 0.34.0 so the released version is now also fixed. Let me know if that does not solve the problem.

**Comment by No-Stream** [comment]
Currently running into this issue with `SHAP == 0.34.0`, `XGBoost == 0.90`.  I haven't seen a tutorial on the mode feature_perturbation='interventional', but providing 100-200 rows of training data for the data field and using this mode, I get the above error (`AssertionError: Additivity check failed in TreeExplainer! Please report this on GitHub.` Note that I don't get it with tree_path_dependent.) I'm able to avoid it by using `check_additivity=False` when extracting the SHAP values.

**Comment by josiahjohnston** [comment]
I'm seeing the identical thing as @No-Stream, except with a RandomForestRegression model. I'm cautious about `check_additivity=False`, so will probably stick with tree_path_dependent for now.

**Comment by LEMTideman** [comment]
Hi @slundberg I have the same problem as @No-Stream and @josiahjohnston. The "Additivity check failed in TreeExplainer! Please report this on Github" error message has also recently been mentioned in issue #1096. I am working on release 0.34.0. I have noticed that checking the additivity property fails only when feature_perturbation = 'interventional'. I get no error when using feature_perturbation = 'tree_path_dependent'. I see that fixing the too tight check_additivity tolerance in TreeExplainer is one of the changes you wanted to include in release 0.34.0, yet there still seems to be a problem...
