### ISSUE TITLE
AssertionError: Explanations do not sum up to the model's output! Please post as a github issue.

### ISSUE THREAD

**Issue by VipinSiriah** [shap/shap#930]
I am trying to get explanations for my LSTM (12 window, 2 features):
```
import shap 
explainer = shap.DeepExplainer(model, features.reshape(48, 2, 12, 1))
shap_values = explainer.shap_values(features.reshape(48, 2, 12, 1))
```

Following is the complete stack of the error :

```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-12-cb83dc7c0499> in <module>
      2 import pandas as pd
      3 explainer = shap.DeepExplainer(model, features.reshape(48, 2, 12, 1))
----> 4 shap_values = explainer.shap_values(features.reshape(48, 2, 12, 1))

D:\Anaconda\lib\site-packages\shap\explainers\deep\__init__.py in shap_values(self, X, ranked_outputs, output_rank_order)
    117         were chosen as "top".
    118         """
--> 119         return self.explainer.shap_values(X, ranked_outputs, output_rank_order)

D:\Anaconda\lib\site-packages\shap\explainers\deep\deep_tf.py in shap_values(self, X, ranked_outputs, output_rank_order, check_additivity)
    283             for l in range(len(X)):
    284                 diffs = model_output[:, l] - self.expected_value[l] - output_phis[l].sum(axis=tuple(range(1, output_phis[l].ndim)))
--> 285                 assert np.abs(diffs).max() < 1e-4, "Explanations do not sum up to the model's output! Please post as a github issue."
    286         if not self.multi_output:
    287             return output_phis[0]
```

**Comment by Jimbotsai** [comment]
Just got the same issue here, too.
I am using shap on my CNN model.
![螢幕快照 2019-12-05 下午3 40 18](https://user-images.githubusercontent.com/42758352/70283335-96fd0c00-1775-11ea-99a7-f4645f2ec2c4.png)
following is the error message
![螢幕快照 2019-12-05 下午3 40 34](https://user-images.githubusercontent.com/42758352/70283340-9b292980-1775-11ea-8efc-7fa64ba5b60b.png)

Update:
Both tf == 2.0 or tf ==1.14 arise this error

**Comment by Jimbotsai** [comment]
Update:
shap 0.31 version is able to get no error. however 0.32 version arises this problem.

**Comment by slundberg** [comment]
Thanks for posting. This check is new in 0.32 and is supposed to verify that nothing went wrong. So it might be catching a real problem or it might be just a numerical tolerance issue. Could you check and see if changing the tolerance from 1e-4 to 1e-2 helps? Also do you have really large model output values? Sometimes that can cause numerical precision issues.

**Comment by VipinSiriah** [comment]
Dear Scott,

I tried with the 10^-2 tolerance in version 0.32. It worked for most of my
models.

But sometimes it was still failing even with 10^-2 tolerance.

While same model and feature set worked well with 0.31 version even with
lower (10^-4) tolerance value.

Please let me know if we have a newer update with this fix.

Also I will take this opportunity to thank and congratulate you for this
amazing work on Shap.

I would like to learn more mathematics behind this that what is available
on websites and NIPS paper.

Thanks & Regards
Vipin Siriah
Data Science Engineer
Bengaluru, India

**Comment by slundberg** [comment]
Hmm, interesting. If it is really close then might just be rounding errors and you can set `check_additivity=False`. I wonder if you have really large model output values? Perhaps huge log-odds numbers?

**Comment by Jimbotsai** [comment]
Dear @slundberg ,
In my case, the error still arise when I set the tolerance to 1e-2 and set check_additivity=False.
And for my model output values, they are just a bunch of numbers in [0,1].
Thank you!

**Comment by slundberg** [comment]
@Jimbotsai That error shouldn't be possible when `check_additivity=False` is passed to shap_values. Perhaps it is a similar looking problem?

**Comment by VipinSiriah** [comment]
My values are scaled between 0 and 1 using min max scaler.

**Comment by slundberg** [comment]
@VipinSiriah If you have small self contained example that is shareable let us know. It could just be some rounding, but it seems worth checking.

**Comment by nyavramov** [comment]
@slundberg Hi,

The following code:
```Python 
explainer.shap_values(data, check_additivity=False)
```
 fails with the error:
```Python 
TypeError:` shap_values() got an unexpected keyword argument 'check_additivity'
```

Am I passing this parameter in correctly? I have pip installed shap==0.33.0

Thank you!

**Comment by slundberg** [comment]
@nyavramov thanks for catching that! I just pushed a fix for that (you can also do `explainer.explainer.shap_values(data, check_additivity=False)` for now)

**Comment by nyavramov** [comment]
@slundberg Awesome, thank you 😄 !

**Comment by amitojbrar** [comment]
@slundberg I am still getting the `TypeError:` shap_values() got an unexpected keyword argument 'check_additivity'` error on 0.34.0. Any fix for it? Went back to 0.31.0 for now.

**Comment by dupsys** [comment]
@slundberg 

The following code:
![Screenshot from 2020-02-27 18-13-46](https://user-images.githubusercontent.com/19542192/75462513-0bb69f80-598d-11ea-89da-4626a24253fd.png)

Am I passing the wrong parameter?.

With check_additivity=False, I got:

TypeError: shap_values() got an unexpected keyword argument 'check_additivity'

Thank you!

**Comment by Zahlii** [comment]
@slundberg In the above-mentioned PR; I also had a look into the problem; however I could only solve some surrounding errors, not the calculation itself. I am assuming that there is a bug / missing custom gradient in some of the implementations.

On closer inspection, I tried setting different op's custom gradient to passthrough and watched whether the gradients became non-zero. **It seems the "Mul" combined with "MatMul" operation currently leads to the zero gradients**, i.e. if I set both to passthrough, gradients are non-zero.



Edit: This seems to be cause by an incorrect calculation of which inputs constitute to the model outputs, i.e. self._vinputs[op] sometimes indicates all inputs are False, i.e. fixed.

Edit: It seems that some of the namings were changed, i.e. the following ops are found by backward_walk_ops:

`BACK ['sequential/dense/BiasAdd', 'sequential/dense/BiasAdd/ReadVariableOp', 'sequential/dense/BiasAdd/ReadVariableOp/resource', 'sequential/dense/MatMul', 'sequential/dense/MatMul/ReadVariableOp', 'sequential/dense/MatMul/ReadVariableOp/resource', 'sequential/flatten/Const', 'sequential/flatten/Reshape', 'sequential/lstm/Shape', 'sequential/lstm/Shape_1', 'sequential/lstm/TensorArrayUnstack/TensorListFromTensor', 'sequential/lstm/TensorArrayUnstack/TensorListFromTensor/element_shape', 'sequential/lstm/TensorArrayV2Stack/TensorListStack', 'sequential/lstm/TensorArrayV2Stack/TensorListStack/element_shape', 'sequential/lstm/TensorArrayV2_1', 'sequential/lstm/TensorArrayV2_1/element_shape', 'sequential/lstm/lstm_cell/BiasAdd/ReadVariableOp/resource', 'sequential/lstm/lstm_cell/MatMul/ReadVariableOp/resource', 'sequential/lstm/lstm_cell/MatMul_1/ReadVariableOp/resource', 'sequential/lstm/strided_slice', 'sequential/lstm/strided_slice/stack', 'sequential/lstm/strided_slice/stack_1', 'sequential/lstm/strided_slice/stack_2', 'sequential/lstm/strided_slice_1', 'sequential/lstm/strided_slice_1/stack', 'sequential/lstm/strided_slice_1/stack_1', 'sequential/lstm/strided_slice_1/stack_2', 'sequential/lstm/time', 'sequential/lstm/transpose', 'sequential/lstm/transpose/perm', 'sequential/lstm/transpose_1', 'sequential/lstm/transpose_1/perm', 'sequential/lstm/while', 'sequential/lstm/while/loop_counter', 'sequential/lstm/while/maximum_iterations', 'sequential/lstm/zeros', 'sequential/lstm/zeros/Const', 'sequential/lstm/zeros/packed', 'sequential/lstm/zeros/packed/1', 'sequential/lstm/zeros_1', 'sequential/lstm/zeros_1/Const', 'sequential/lstm/zeros_1/packed', 'sequential/lstm/zeros_1/packed/1', 'shap_rAnD', 'strided_slice', 'strided_slice/stack', 'strided_slice/stack_1', 'strided_slice/stack_2']`

However, the unrolled op names are `Mul IN ['sequential/lstm/while/lstm_cell/Sigmoid_2:0', 'sequential/lstm/while/lstm_cell/add_1:0']`
These are then not found inside the between_tensors, and thus set to "fixed" for the _variable_inputs funtion, which yields zero gradients.


Trying to find the respective upstream changes.
https://github.com/tensorflow/tensorflow/commit/a3116681da4cc86afcf1675f94233b1593ff6fe4#diff-e329ed6b8d30dca9a441689005047035
 and possibly this https://github.com/tensorflow/tensorflow/commit/0e1f3de50a5c22bfb871d76d306770eb283be95d#diff-e329ed6b8d30dca9a441689005047035

**Comment by Zahlii** [comment]
If I modify the code as follows, the gradients are not zero; however the additivity still doesn't hold (fully).

On my toy example, I get an error (PRED-SHAP)/PREC of on average 0.16%

```python
def _variable_inputs(self, op):
        """Return which inputs of this operation are variable (i.e. depend on the model inputs)."""
        if op not in self._vinputs:
            print(op.type, "IN", [t.name for t in op.inputs])
            out = np.zeros(len(op.inputs), dtype=np.bool)
            for i, t in enumerate(op.inputs):
                out[i] = t.name in self.between_tensors
                if not out[i]:
                    if "lstm/while/lstm_cell" in t.name:
                        out[i] = True
            self._vinputs[op] = out

        return self._vinputs[op]
```
