### ISSUE TITLE
"ValueError: minvalue must be less than or equal to maxvalue" when calling summary_plot

### ISSUE THREAD

**Issue by daanpdebruin** [shap/shap#971]
This can happens when all shap_values of a feature are equal.

In summary_plot vmin and vmax are calculated like this:

`vmin = np.nanpercentile(values, 5)`
`vmax = np.nanpercentile(values, 95)`

This results in vmin being equal to vmax when all values are equal. However due to rounding differences, sometimes vmin > vmax at ~ the 10th decimal place. This results in matplotlib colors error
Would be solved by rounding vmin and vmax to a certain number of digits (for example 5)

```
ValueError                                Traceback (most recent call last)
~/.conda/envs/project-cards/lib/python3.6/site-packages/IPython/core/formatters.py in __call__(self, obj)
    339                 pass
    340             else:
--> 341                 return printer(obj)
    342             # Finally look for special method names
    343             method = get_real_method(obj, self.print_method)
~/.conda/envs/project-cards/lib/python3.6/site-packages/IPython/core/pylabtools.py in <lambda>(fig)
    242 
    243     if 'png' in formats:
--> 244         png_formatter.for_type(Figure, lambda fig: print_figure(fig, 'png', **kwargs))
    245     if 'retina' in formats or 'png2x' in formats:
    246         png_formatter.for_type(Figure, lambda fig: retina_figure(fig, **kwargs))
~/.conda/envs/project-cards/lib/python3.6/site-packages/IPython/core/pylabtools.py in print_figure(fig, fmt, bbox_inches, **kwargs)
    126 
    127     bytes_io = BytesIO()
--> 128     fig.canvas.print_figure(bytes_io, **kw)
    129     data = bytes_io.getvalue()
    130     if fmt == 'svg':
~/.conda/envs/project-cards/lib/python3.6/site-packages/matplotlib/backend_bases.py in print_figure(self, filename, dpi, facecolor, edgecolor, orientation, format, bbox_inches, **kwargs)
   2054                         orientation=orientation,
   2055                         dryrun=True,
-> 2056                         **kwargs)
   2057                     renderer = self.figure._cachedRenderer
   2058                     bbox_artists = kwargs.pop("bbox_extra_artists", None)
~/.conda/envs/project-cards/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py in print_png(self, filename_or_obj, metadata, pil_kwargs, *args, **kwargs)
    525 
    526         else:
--> 527             FigureCanvasAgg.draw(self)
    528             renderer = self.get_renderer()
    529             with cbook._setattr_cm(renderer, dpi=self.figure.dpi), \
~/.conda/envs/project-cards/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py in draw(self)
    386         self.renderer = self.get_renderer(cleared=True)
    387         with RendererAgg.lock:
--> 388             self.figure.draw(self.renderer)
    389             # A GUI class may be need to update a window using this draw, so
    390             # don't forget to call the superclass.
~/.conda/envs/project-cards/lib/python3.6/site-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     36                 renderer.start_filter()
     37 
---> 38             return draw(artist, renderer, *args, **kwargs)
     39         finally:
     40             if artist.get_agg_filter() is not None:
~/.conda/envs/project-cards/lib/python3.6/site-packages/matplotlib/figure.py in draw(self, renderer)
   1707             self.patch.draw(renderer)
   1708             mimage._draw_list_compositing_images(
-> 1709                 renderer, self, artists, self.suppressComposite)
   1710 
   1711             renderer.close_group('figure')
~/.conda/envs/project-cards/lib/python3.6/site-packages/matplotlib/image.py in _draw_list_compositing_images(renderer, parent, artists, suppress_composite)
    133     if not_composite or not has_images:
    134         for a in artists:
--> 135             a.draw(renderer)
    136     else:
    137         # Composite any adjacent images together
~/.conda/envs/project-cards/lib/python3.6/site-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     36                 renderer.start_filter()
     37 
---> 38             return draw(artist, renderer, *args, **kwargs)
     39         finally:
     40             if artist.get_agg_filter() is not None:
~/.conda/envs/project-cards/lib/python3.6/site-packages/matplotlib/axes/_base.py in draw(self, renderer, inframe)
   2645             renderer.stop_rasterizing()
   2646 
-> 2647         mimage._draw_list_compositing_images(renderer, self, artists)
   2648 
   2649         renderer.close_group('axes')
~/.conda/envs/project-cards/lib/python3.6/site-packages/matplotlib/image.py in _draw_list_compositing_images(renderer, parent, artists, suppress_composite)
    133     if not_composite or not has_images:
    134         for a in artists:
--> 135             a.draw(renderer)
    136     else:
    137         # Composite any adjacent images together
~/.conda/envs/project-cards/lib/python3.6/site-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     36                 renderer.start_filter()
     37 
---> 38             return draw(artist, renderer, *args, **kwargs)
     39         finally:
     40             if artist.get_agg_filter() is not None:
~/.conda/envs/project-cards/lib/python3.6/site-packages/matplotlib/collections.py in draw(self, renderer)
    864     def draw(self, renderer):
    865         self.set_sizes(self._sizes, self.figure.dpi)
--> 866         Collection.draw(self, renderer)
    867 
    868 
~/.conda/envs/project-cards/lib/python3.6/site-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     36                 renderer.start_filter()
     37 
---> 38             return draw(artist, renderer, *args, **kwargs)
     39         finally:
     40             if artist.get_agg_filter() is not None:
~/.conda/envs/project-cards/lib/python3.6/site-packages/matplotlib/collections.py in draw(self, renderer)
    253         renderer.open_group(self.__class__.__name__, self.get_gid())
    254 
--> 255         self.update_scalarmappable()
    256 
    257         transform, transOffset, offsets, paths = self._prepare_points()
~/.conda/envs/project-cards/lib/python3.6/site-packages/matplotlib/collections.py in update_scalarmappable(self)
    761             return
    762         if self._is_filled:
--> 763             self._facecolors = self.to_rgba(self._A, self._alpha)
    764         elif self._is_stroked:
    765             self._edgecolors = self.to_rgba(self._A, self._alpha)
~/.conda/envs/project-cards/lib/python3.6/site-packages/matplotlib/cm.py in to_rgba(self, x, alpha, bytes, norm)
    287         x = ma.asarray(x)
    288         if norm:
--> 289             x = self.norm(x)
    290         rgba = self.cmap(x, alpha=alpha, bytes=bytes)
    291         return rgba
~/.conda/envs/project-cards/lib/python3.6/site-packages/matplotlib/colors.py in __call__(self, value, clip)
    962             result.fill(0)   # Or should it be all masked?  Or 0.5?
    963         elif vmin > vmax:
--> 964             raise ValueError("minvalue must be less than or equal to maxvalue")
    965         else:
    966             if clip:
ValueError: minvalue must be less than or equal to maxvalue
```

**Comment by daanpdebruin** [comment]
closing, since I found out that this is fixed recently in #914 and will be part of the next release

**Comment by AGG2016** [comment]
Was this issue solved? I downloaded the package recently and it seems that the bug is still there.
